services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      MONGO_URI: mongodb://mongodb:27017/tutorialdb
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data: